# Generated by Django 5.0.2 on 2025-03-14 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_eventstockallocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charity',
            name='location',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
    ]
