# Generated by Django 5.0.2 on 2025-03-14 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_charity_location_remove_event_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='stock_allocation',
        ),
    ]
