# Generated by Django 5.0.2 on 2025-03-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_usertask'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seil',
            field=models.IntegerField(default=10),
        ),
    ]
