# Generated by Django 5.0.2 on 2025-03-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_product_seil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seil',
            field=models.IntegerField(default=33),
        ),
    ]
